name: Foundry tests

on:
    push:
      branches:
      - master
    pull_request:
  
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        architecture:
          - "x64"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Install Vyper
        run: pip install vyper==0.3.7

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Foundry tests
        run: forge test -vvv