name: Lint

on:
  push:
    branches:
    - master
  pull_request:

jobs:
    commits:
      runs-on: ubuntu-latest

      steps:
      - name: Check out github repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@4b1bcb1c72f99fbd6aa6b34cc3fb59200f01f993 # v2

    black:
      runs-on: ubuntu-latest

      steps:
      - name: Check out github repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 1

      - name: Set up python 3.9
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
          python-version: 3.9

      - name: Set pip cache directory path
        id: pip-cache-dir-path
        run: |
            echo "::set-output name=dir::$(pip cache dir)"
      - name: Restore pip cache
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        id: pip-cache
        with:
          path: |
            ${{ steps.pip-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-
      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run black
        run: black --check .