name: Slither Analysis
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: crytic/slither-action@16fe6d29d16c34999bccbd16090a7c7cba6a9c3e # v0.1.1
        continue-on-error: true